/**
 * Domain keyword dictionaries for fallback keyword-based analysis
 *
 * Based on query-analyzer.md v1.0 with refinements from dry run testing
 * Total: 196 keywords across 6 domains
 */

import type { AgentType, DomainAgentMap, KeywordDictionary } from './types.ts';

export const DOMAIN_KEYWORDS: KeywordDictionary = {
  social_media: [
    'twitter',
    'x',
    'social media',
    'reddit',
    'facebook',
    'instagram',
    'trending',
    'viral',
    'hashtag',
    'community',
    'discussion',
    'sentiment',
    'public opinion',
    'discourse',
    'conversation',
    'influencer',
    'engagement',
    'post',
    'thread',
    'comment',
    'tiktok',
    'linkedin',
    'mastodon',
    'social network',
    'perception',
    'opinion',
    'public',
    'consensus',
    'debate',
    'trending topic',
    'viral topic',
    'buzz',
    'hype',
  ],

  academic: [
    'research',
    'paper',
    'study',
    'journal',
    'arxiv',
    'academic',
    'peer review',
    'citation',
    'publication',
    'scholar',
    'methodology',
    'framework',
    'theory',
    'analysis',
    'evidence',
    'empirical',
    'experiment',
    'findings',
    'literature review',
    'systematic review',
    'dissertation',
    'thesis',
    'conference',
    'proceedings',
    'compare',
    'comparison',
    'versus',
    'vs',
    'differences',
    'similarities',
    'breakthrough',
    'discovery',
    'advance',
    'innovation',
    'novel',
  ],

  technical: [
    'implementation',
    'code',
    'api',
    'framework',
    'library',
    'architecture',
    'system',
    'algorithm',
    'programming',
    'development',
    'software',
    'technical',
    'engineering',
    'design pattern',
    'performance',
    'optimization',
    'debug',
    'integration',
    'deployment',
    'infrastructure',
    'tools',
    'data',
    'platform',
    'service',
    'database',
    'pipeline',
    'workflow',
    'automation',
    'devops',
    // Web/Frontend
    'server',
    'client',
    'component',
    'frontend',
    'backend',
    'react',
    'vue',
    'angular',
    'node',
    'express',
    'next',
    // AI/ML
    'AI',
    'LLM',
    'machine learning',
    'model',
    'agent',
    'neural',
    'GPT',
    'transformer',
    'training',
    'inference',
    // Hardware/Computing
    'computing',
    'quantum',
    'processor',
    'chip',
    'hardware',
    'GPU',
    'CPU',
    'cloud',
    'distributed',
    // Languages
    'python',
    'javascript',
    'typescript',
    'rust',
    'go',
    'java',
    'c++',
    'c#',
    'ruby',
    'php',
    'swift',
    'kotlin',
    // Companies/Products (Top tech entities)
    'OpenAI',
    'Anthropic',
    'Google',
    'Microsoft',
    'AWS',
    'Azure',
    'Meta',
    'Apple',
    'Amazon',
    'GitHub',
    'Docker',
    'Kubernetes',
  ],

  multimodal: [
    'video',
    'image',
    'visual',
    'youtube',
    'tutorial',
    'demonstration',
    'diagram',
    'infographic',
    'screenshot',
    'visualization',
    'chart',
    'graph',
    'illustration',
    'animation',
    'presentation',
    'multimedia',
    'gallery',
    'graphics',
    'design',
    'UI',
    'UX',
  ],

  security: [
    'OSINT',
    'threat',
    'intelligence',
    'vulnerability',
    'exploit',
    'cybersecurity',
    'infosec',
    'hacking',
    'penetration',
    'pentest',
    'reconnaissance',
    'forensics',
    'malware',
    'attack',
    'breach',
    'security',
    'privacy',
    'encryption',
    'authentication',
    'authorization',
    'CTF',
    'red team',
    'blue team',
    'threat actor',
    'IOC',
    'indicator',
  ],

  news: [
    'news',
    'breaking',
    'current',
    'latest',
    'update',
    'announcement',
    'event',
    'happening',
    'today',
    'recent',
    'development',
    'report',
    'coverage',
    'journalism',
    'article',
    'press release',
    'headline',
  ],
};

/**
 * Map domains to preferred agent types for Wave 1 allocation
 */
export const DOMAIN_AGENT_MAP: DomainAgentMap = {
  social_media: 'grok-researcher',
  academic: 'perplexity-researcher',
  technical: 'claude-researcher',
  multimodal: 'gemini-researcher',
  security: 'perplexity-researcher', // Threat intel = research-heavy
  news: 'perplexity-researcher',
};

/**
 * Complexity thresholds for agent count determination
 */
export const COMPLEXITY_THRESHOLDS = {
  SIMPLE: 2, // 1-2 keyword matches → 4 agents
  MODERATE: 5, // 3-5 keyword matches → 5 agents
  COMPLEX: 6, // 6+ keyword matches → 6 agents
} as const;

/**
 * Primary specialist allocation percentage (of total Wave 1 agents)
 */
export const PRIMARY_SPECIALIST_PERCENTAGE = 0.35;

/**
 * Generalist agent priority order for filling remaining slots
 */
export const GENERALIST_PRIORITY: AgentType[] = [
  'perplexity-researcher',
  'claude-researcher',
  'gemini-researcher',
];
